Remove dependency on bash, simplify code & license.

diff --git a/newcsr b/newcsr
--- a/newcsr
+++ b/newcsr
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 set -e
 
@@ -7,27 +7,56 @@ usage() {
   echo "Usage:"
   echo "  $(basename $0) [-h|--help]"
   echo "    This help"
-  echo "  $(basename $0) [-p <pkidir>] [-x <extensions>] <key-name>"
-  echo "    Create a key with a signing request for CA"
-  echo "    -p: Base directory for PKI data"
+  echo "  $(basename $0) [-p <pkidir>] [-x <extensions>]"
+  echo "          [-k <key-file>] (-o <outfile> | <key-name>)"
+  echo "    Create a signing request from a key"
+  echo "    -k: Alternate key file path"
+  echo "    -o: Output file (default requests/<name>)"
+  echo "    -p: Base directory for PKI data (default \$PKIDIR)"
   echo "    -x: Extensions section to use"
   if [ "$e" ]; then exit $e; fi
 }
 
-unset pkidir bits
+unset pkidir
+unset keyfile extensions outfile
 
 if [ "$1" = "--help" ]; then usage 0; fi
-while getopts "hp:x:" arg; do
+while getopts "hk:o:p:x:" arg; do
   case $arg in
     h) usage 0 ;;
+    k) keyfile=$OPTARG ;;
+    o) outfile=$OPTARG ;;
     p) pkidir=$OPTARG ;;
     x) extensions=$OPTARG ;;
     ?) usage 1 ;;
   esac
 done
 shift $(expr $OPTIND - 1)
-name="$1"
 
-cd ${pkidir:-${PKIDIR:?No PKI working directory}}
+name=$1
+# No / or NUL characters to protect the filesystem. If you screw up the
+# config file that's your lookout.
+fs_name=$(echo "$name" | tr '\000/' _)
 
-openssl req -new -config pki.conf -text -key keys/"${name//\//_}" -out requests/"${name//\//_}" ${extensions:+-reqexts $extensions}
+if [ -z "$keyfile" -o -n "$outfile" ]; then
+  cd "${pkidir:=${PKIDIR:?No PKI working directory}}"
+fi
+
+if [ -z "$outfile" ]; then
+  if [ -n "$name" ]; then
+    outfile=requests/"$fs_name"
+  else
+    outfile=$keyfile.csr
+  fi
+fi
+
+if [ -z "$keyfile" ]; then
+  if [ -n "$name" ]; then
+    keyfile=keys/"$fs_name"
+  else
+    echo "Cannot find key file." >&2
+    exit 1
+  fi
+fi
+
+openssl req -new -config pki.conf -text -key "$keyfile" -out "$outfile" ${extensions:+-reqexts $extensions}
diff --git a/newkey b/newkey
--- a/newkey
+++ b/newkey
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 set -e
 
@@ -7,52 +7,69 @@ usage() {
   echo "Usage:"
   echo "  $(basename $0) [-h|--help]"
   echo "    This help"
-  echo "  $(basename $0) [-p <pkidir>] [(-e|-E) [-a <algorithm>]] [-b <bits>] <key-name>"
-  echo "    Create a key with a signing request for CA"
-  echo "    -p: Base directory for PKI data"
-  echo "    -e: Encrypt the private key"
-  echo "    -E: As above but include the unencrypted and expanded forms"
+  echo "  $(basename $0) [-p <pkidir>] [(-n|-N)] [-a <algorithm>]"
+  echo "            [-b <bits>] (-o <outfile> | <key-name>)"
+  echo "    Create a private key, optionally unencrypted"
   echo "    -a: Encryption algorithm to use (default des3)"
-  echo "    -b: Key size. No default except openssl's 512."
+  echo "    -b: Key size. No default here; openssl's default is (currently) 512"
+  echo "    -n: Don't encrypt the key (default is to encrypt)"
+  echo "    -N: Encrypt as normal but also place an unencrypted key in unencrypted-<key>"
+  echo "    -o: File to save key to (default \$PKIDIR/keys/<name>)"
+  echo "    -p: Base directory for PKI data (default \$PKIDIR)"
   if [ "$e" ]; then exit $e; fi
 }
 
-unset pkidir bits
-encrypt=0
+unset pkidir bits outfile
+encrypt=yes
 algorithm=des3
 
 if [ "$1" = "--help" ]; then usage 0; fi
-while getopts "hp:eEa:b:" arg; do
+while getopts "ha:b:nNo:p:" arg; do
   case $arg in
     h) usage 0 ;;
-    p) pkidir=$OPTARG ;;
-    e) encrypt=-1 ;;
-    E) encrypt=1 ;;
     a) algorithm=$OPTARG ;;
     b) bits=$OPTARG ;;
+    n) encrypt=no ;;
+    N) encrypt=both ;;
+    o) outfile=$OPTARG ;;
+    p) pkidir=$OPTARG ;;
     ?) usage 1 ;;
   esac
 done
 shift $(expr $OPTIND - 1)
-name="$1"
 
-cd ${pkidir:-${PKIDIR:?No PKI working directory}}
-if ! tmp=$(mktemp --tmpdir=tmp -d); then
-  echo Cannot create temporary directory. >&2
+if [ -z "$outfile" ]; then
+  : ${pkidir:=${PKIDIR:?No PKI working directory}}
+  cd "$pkidir"
+  name="${1:?No key name}"
+  # No / or NUL characters to protect the filesystem. If you screw up the
+  # config file that's your lookout.
+  fs_name=$(echo "$name" | tr '\000/' _)
+  outfile="keys/$fs_name"
+fi
+
+# Use TMPDIR to ensure this is kept away from non-volatile if necessary.
+if ! tmp=$(mktemp -t -d); then
+  echo "Cannot create temporary directory." >&2
   exit 2
 fi
 trap "rm -fr $tmp" EXIT
 
 umask 377
-openssl genrsa -out "$tmp"/key $bits
-if (( $encrypt >= 0 )); then
-  openssl rsa -in "$tmp"/key -text -out keys/"${name//\//_}"
-  if (( $encrypt )); then
-    openssl rsa -in "$tmp"/key -$algorithm -out keys/encrypted-"${name//\//_}"
-    chmod u+w keys/"${name//\//_}"
-    cat keys/encrypted-"${name//\//_}" >> keys/"${name//\//_}"
-    chmod u-w keys/"${name//\//_}"
-  fi
-else
-  openssl rsa -in "$tmp"/key -$algorithm -out keys/"${name//\//_}"
-fi
+echo Encrypt: $encrypt
+case $encrypt in
+  no)
+    openssl genrsa -out "$tmp"/unencrypted-key $bits
+    openssl rsa -in "$tmp"/unencrypted-key -text -out "$outfile"
+    ;;
+  yes)
+    openssl genrsa $bits | openssl rsa -$algorithm -out "$tmp"/encrypted-key
+    mv "$tmp"/encrypted-key "$outfile"
+    ;;
+  both)
+    openssl genrsa -out "$tmp"/unencrypted-key $bits
+    openssl rsa -in "$tmp"/unencrypted-key -$algorithm -out "$tmp"/encrypted-key
+    mv "$tmp"/encrypted-key "$outfile"
+    openssl rsa -in "$tmp"/unencrypted-key -text -out "$(dirname "$outfile")"/unencrypted-"$(basename "$outfile")"
+    ;;
+esac
diff --git a/sign b/sign
--- a/sign
+++ b/sign
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 
 set -e
 
@@ -8,63 +8,53 @@ usage() {
   echo "  $(basename $0) [-h|--help]"
   echo "    This help"
   echo "  $(basename $0) [-p <pkidir>] [-x <extensions>] [-P <policy>]"
-  echo "      Self-signed certificates:"
-  echo "                 -S <request-name>"
-  echo "      CA-signed certificates:"
-  echo "                 -c <ca> [-r] <request-name>"
-  echo "    Sign request as CA"
-  echo "    -p: Base directory for PKI data"
+  echo "      (-s | -c <ca>) [-k <keyfile>] <request-name>"
+  echo "    Sign request as CA (-c) or self-sign (-s)"
   echo "    -c: Certificate Authority"
-  echo "    -x: Section of config file with extensions to apply to certificate"
+  echo "    -k: Alternate key file"
+  echo "    -p: Base directory for PKI data"
   echo "    -P: Section of config file defining certificate policy"
-  echo "    -r: (default action): name of CSR to sign"
-  echo "    -S: Sign the CSR with the key that generated it (self-signed certificate)"
+  echo "    -s: Sign the CSR with the key that generated it (self-signed certificate)"
+  echo "    -x: Section of config file with extensions to apply to certificate"
   if [ "$e" ]; then exit $e; fi
 }
 
-unset action name
-unset pkidir ca extensions policy
-
-set_action() {
-  if [ "$action" ]; then
-    echo "Cannot set conflicting actions" >&2
-    exit 1
-  fi
-  action="$1"
-}
+unset pkidir name
+unset ca keyfile policy selfsign extensions
 
 if [ "$1" = "--help" ]; then usage 0; fi
-while getopts "hp:c:x:P:r:S:" arg; do
+while getopts "hc:k:p:P:sx:" arg; do
   case $arg in
     h) usage 0 ;;
+    c) export ca=$(echo "$OPTARG" | tr '\000/' _) ;;
+    k) keyfile=$OPTARG ;;
     p) pkidir=$OPTARG ;;
-    x) extensions=$OPTARG ;;
     P) policy=$OPTARG ;;
-    S)
-      set_action selfsign
-      name=$OPTARG
-      ;;
-    r)
-      set_action request
-      name=$OPTARG
-      ;;
-    c) export ca=${OPTARG//\//_} ;;
+    s) selfsign=-selfsign ;;
+    x) extensions=$OPTARG ;;
     ?) usage 1 ;;
   esac
 done
 shift $(expr $OPTIND - 1)
-if [ -z "$name" ]; then set_action request; name=$1; fi
-if [ "$action" = request -a -z "$ca" ]; then usage 1; fi
+name=$1
+# No / or NUL characters to protect the filesystem. If you screw up the
+# config file that's your lookout.
+fs_name=$(echo "$name" | tr '\000/' _)
 
-cd ${pkidir:-${PKIDIR:?No PKI working directory}}
+cd "${pkidir:=${PKIDIR:?No PKI working directory}}"
 
-case $action in
-  request)
-    openssl ca -config pki.conf -in requests/"${name//\//_}" -out certificates/"${name//\//_}" ${extensions:+-extensions $extensions} ${policy:+-policy $policy}
-    ;;
-  selfsign)
-    export ca=${name//\//_}
-    openssl ca -config pki.conf -selfsign -keyfile keys/"${name//\//_}" -in requests/"${name//\//_}" -out certificates/"${name//\//_}" ${extensions:+-extensions $extensions} ${policy:+-policy $policy}
-    ;;
-esac
+if [ -n "$selfsign" ]; then
+  export ca=$fs_name
+fi
 
+# Use TMPDIR to ensure this is kept away from non-volatile if necessary.
+if ! tmp=$(mktemp -t -d); then
+  echo "Cannot create temporary directory." >&2
+  exit 2
+fi
+trap "rm -fr $tmp" EXIT
+
+openssl ca -config pki.conf $selfsign ${keyfile:+-keyfile "$keyfile"}   \
+    -in requests/"$fs_name" -out "$tmp"/certificate                     \
+    ${extensions:+-extensions $extensions} ${policy:+-policy $policy}
+mv "$tmp"/certificate certificates/"$fs_name"
